// Master list of all landmarks with type and difficulty
let landmarks = [
    // Easy landmarks
    { name: "Pashupatinath Temple", image: "Images/Easy/pashupati.png", difficulty: "Easy", type: "Temple" },
    { name: "Boudhanath Stupa", image: "Images/Easy/boudha.png", difficulty: "Easy", type: "Temple" },
    { name: "Swayambhunath Stupa", image: "Images/Easy/swayambhu.png", difficulty: "Easy", type: "Temple" },
    { name: "Kathmandu Durbar Square", image: "Images/Easy/ktm-dsq.png", difficulty: "Easy", type: "Palace" },
    { name: "Patan Durbar Square", image: "Images/Easy/patan-dsq.png", difficulty: "Easy", type: "Palace" },
    { name: "Bhaktapur Durbar Square", image: "Images/Easy/bkt-dsq.png", difficulty: "Easy", type: "Palace" },
    { name: "Dharahara Tower", image: "Images/Easy/dharahara.png", difficulty: "Easy", type: "Tower" },
    { name: "Janaki Temple", image: "Images/Easy/janaki.png", difficulty: "Easy", type: "Temple" },
    { name: "Maya Devi Temple", image: "Images/Easy/mdt.png", difficulty: "Easy", type: "Temple" },
    { name: "Mount Everest", image: "Images/Easy/mtev.png", difficulty: "Easy", type: "Mountain" },
    { name: "Annapurna Base Camp", image: "Images/Easy/abc.png", difficulty: "Easy", type: "Mountain" },
    { name: "Everest Base Camp", image: "Images/Easy/ebc.png", difficulty: "Easy", type: "Mountain" },
    { name: "Phewa Lake", image: "Images/Easy/phewa.png", difficulty: "Easy", type: "Lake" },
    { name: "Tal Barahi Temple", image: "Images/Easy/tbt.png", difficulty: "Easy", type: "Temple" },
    { name: "Bindhyabasini Temple", image: "Images/Easy/bindyabasini.png", difficulty: "Easy", type: "Temple" },
    { name: "Manakamana Temple", image: "Images/Easy/manakamana.png", difficulty: "Easy", type: "Temple" },
    { name: "Budhanilkantha Temple", image: "Images/Easy/budhanilkantha.png", difficulty: "Easy", type: "Temple" },
    { name: "Dakshinkali Temple", image: "Images/Easy/dakshinkali.png", difficulty: "Easy", type: "Temple" },
    { name: "Narayanhiti Palace Museum", image: "Images/Easy/narayanhiti.png", difficulty: "Easy", type: "Palace" },
    { name: "Garden of Dreams", image: "Images/Easy/god.png", difficulty: "Easy", type: "Garden" },
    { name: "World Peace Pagoda", image: "Images/Easy/wpp.png", difficulty: "Easy", type: "Temple" },
    { name: "Sarangkot Temple", image: "Images/Easy/st.png", difficulty: "Easy", type: "Temple" },
    { name: "Chitwan National Park", image: "Images/Easy/cnp.png", difficulty: "Easy", type: "Wildlife" },
    { name: "Rara Lake", image: "Images/Easy/rara.png", difficulty: "Easy", type: "Lake" },
    { name: "Shey Phoksundo Lake", image: "Images/Easy/spl.png", difficulty: "Easy", type: "Lake" },
    { name: "Gosaikunda Lake", image: "Images/Easy/gkl.png", difficulty: "Easy", type: "Lake" },
    { name: "Annapurna I", image: "Images/Easy/a1.png", difficulty: "Easy", type: "Mountain" },
    { name: "Machapuchare", image: "Images/Easy/mp.png", difficulty: "Easy", type: "Mountain" },
    { name: "Manaslu", image: "Images/Easy/manaslu.png", difficulty: "Easy", type: "Mountain" },
    { name: "Dhaulagiri", image: "Images/Easy/dhaulagiri.png", difficulty: "Easy", type: "Mountain" },
    { name: "Ilam Tea Gardens", image: "Images/Easy/itg.png", difficulty: "Easy", type: "Garden" },
    { name: "Ghandruk Village", image: "Images/Easy/ghandruk.png", difficulty: "Easy", type: "Village" },
    { name: "Bandipur Village", image: "Images/Easy/bandipur.png", difficulty: "Easy", type: "Village" },
    { name: "Seti Gorge", image: "Images/Easy/seti.png", difficulty: "Easy", type: "River" },
    { name: "International Mountain Museum", image: "Images/Easy/imm.png", difficulty: "Easy", type: "Museum" },

    // Medium landmarks
    { name: "Nyatapola Temple", image: "Images/Medium/nytatapola.png", difficulty: "Medium", type: "Temple" },
    { name: "Dattatreya Temple", image: "Images/Medium/datatraye.png", difficulty: "Medium", type: "Temple" },
    { name: "Taleju Temple", image: "Images/Medium/taleju.png", difficulty: "Medium", type: "Temple" },
    { name: "Changu Narayan Temple", image: "Images/Medium/changu.png", difficulty: "Medium", type: "Temple" },
    { name: "Kasthamandap", image: "Images/Medium/kasthamandap.png", difficulty: "Medium", type: "Temple" },
    { name: "Hanuman Dhoka Palace", image: "Images/Medium/hd.png", difficulty: "Medium", type: "Palace" },
    { name: "Rani Pokhari", image: "Images/Medium/rp-ktm.png", difficulty: "Medium", type: "Temple" },
    { name: "Begnas Lake", image: "Images/Medium/begnas.png", difficulty: "Medium", type: "Lake" },
    { name: "Rupa Lake", image: "Images/Medium/rupa.png", difficulty: "Medium", type: "Lake" },
    { name: "Devi’s Fall", image: "Images/Medium/df.png", difficulty: "Medium", type: "Waterfall" },
    { name: "Gupteshwor Cave", image: "Images/Medium/gc.png", difficulty: "Medium", type: "Cave" },
    { name: "Ram Mandir", image: "Images/Medium/jrt.png", difficulty: "Medium", type: "Temple" },
    { name: "Vivah Mandap", image: "Images/Medium/bm.png", difficulty: "Medium", type: "Temple" },
    { name: "Ashoka Pillar Lumbini", image: "Images/Medium/apl.png", difficulty: "Medium", type: "Monument" },
    { name: "Thai Monastery Lumbini", image: "Images/Medium/tml.png", difficulty: "Medium", type: "Monastery" },
    { name: "Korean Monastery Lumbini", image: "Images/Medium/kml.png", difficulty: "Medium", type: "Monastery" },
    { name: "Eternal Peace Flame", image: "Images/Medium/epf.png", difficulty: "Medium", type: "Monument" },
    { name: "Tengboche Monastery", image: "Images/Medium/tm.png", difficulty: "Medium", type: "Monastery" },
    { name: "Namche Bazaar", image: "Images/Medium/nb.png", difficulty: "Medium", type: "Village" },
    { name: "Kala Patthar", image: "Images/Medium/kp.png", difficulty: "Medium", type: "Mountain" },
    { name: "Khumbu Glacier", image: "Images/Medium/kg.png", difficulty: "Medium", type: "Glacier" },
    { name: "Gorkha Durbar", image: "Images/Medium/gd.png", difficulty: "Medium", type: "Palace" },
    { name: "Pathibhara Temple", image: "Images/Medium/pt.png", difficulty: "Medium", type: "Temple" },
    { name: "Halesi Mahadev Temple", image: "Images/Medium/hmt.png", difficulty: "Medium", type: "Temple" },
    { name: "Budha Subba Temple", image: "Images/Medium/bst.png", difficulty: "Medium", type: "Temple" },
    { name: "Baraha Kshetra Temple", image: "Images/Medium/bkt.png", difficulty: "Medium", type: "Temple" },
    { name: "Dolakha Bhimsen Temple", image: "Images/Medium/dbt.png", difficulty: "Medium", type: "Temple" },
    { name: "Tansen Durbar", image: "Images/Medium/td.png", difficulty: "Medium", type: "Palace" },
    { name: "Chandragiri Hill", image: "Images/Medium/ch.png", difficulty: "Medium", type: "Hill" },
    { name: "Kalinchowk Bhagwati Temple", image: "Images/Medium/kbt.png", difficulty: "Medium", type: "Temple" },
    { name: "Shivapuri National Park", image: "Images/Medium/snp.png", difficulty: "Medium", type: "Park" },
    { name: "Langtang National Park", image: "Images/Medium/ltp.png", difficulty: "Medium", type: "Park" },

    // Hard landmarks
    { name: "Kagbeni Village", image: "Images/Hard/kv.png", difficulty: "Hard", type: "Village" },
    { name: "Lo Manthang Palace", image: "Images/Hard/lmp.png", difficulty: "Hard", type: "Palace" },
    { name: "Jomsom Village", image: "Images/Hard/j.png", difficulty: "Hard", type: "Village" },
    { name: "Thorong La Pass", image: "Images/Hard/tlp.png", difficulty: "Hard", type: "Mountain" },
    { name: "Tilicho Lake", image: "Images/Hard/tilicho.png", difficulty: "Hard", type: "Lake" },
    { name: "Machapuchare Base Camp", image: "Images/Hard/mbc.png", difficulty: "Hard", type: "Mountain" },
    { name: "Gokyo Lake", image: "Images/Hard/gl.png", difficulty: "Hard", type: "Lake" },
    { name: "Marpha Village", image: "Images/Hard/mv.png", difficulty: "Hard", type: "Village" },
    { name: "Ghalegaun Village", image: "Images/Hard/gv.png", difficulty: "Hard", type: "Village" },
    { name: "Nuwakot Durbar", image: "Images/Hard/nd.png", difficulty: "Hard", type: "Palace" },
    { name: "Lamjung Durbar", image: "Images/Hard/ld.png", difficulty: "Hard", type: "Palace" },
    { name: "Shree Antu Viewpoint", image: "Images/Hard/sav.png", difficulty: "Hard", type: "Hill" },
    { name: "Bhedetar View Tower", image: "Images/Hard/bvt.png", difficulty: "Hard", type: "Tower" },
    { name: "Koshi Tappu Wildlife Reserve", image: "Images/Hard/ktwr.png", difficulty: "Hard", type: "Wildlife" },
    { name: "Hyatung Waterfall", image: "Images/Hard/hw.png", difficulty: "Hard", type: "Waterfall" },
    { name: "Jalbire Waterfall", image: "Images/Hard/jw.png", difficulty: "Hard", type: "Waterfall" },
    { name: "Rupse Waterfall", image: "Images/Hard/rwf.png", difficulty: "Hard", type: "Waterfall" },
    { name: "Bhote Koshi River", image: "Images/Hard/bkr.png", difficulty: "Hard", type: "River" },
    { name: "Trishuli River", image: "Images/Hard/tr.png", difficulty: "Hard", type: "River" },
    { name: "Ganga Sagar", image: "Images/Hard/gsj.png", difficulty: "Hard", type: "Lake" }
];
